version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-laravel-app
    container_name: my-laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: nginx-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network  
       
  # Redis Server   
  redis:
    image: redis:latest
    ports:
      - "6370:6379"
  # websocket   
  websocket:
    build:
        context: .
        args:
            - APP_ENV=${APP_ENV}
    environment:
        - APP_ENV=${APP_ENV}
        - CONTAINER_ROLE=websocket
    working_dir: /var/www
    volumes:
        - ./:/var/www
    ports:
        - 6001:6001

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
