FROM php:8.3-fpm

# Install dependencies
RUN apt-get update && apt-get install -y \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libwebp-dev \
    libxpm-dev \
    libzip-dev \
    zip \
    unzip \
    curl \
    libonig-dev \ 
    git \
    cron
    

# Configure and install GD extension
RUN docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp --with-xpm \
    && docker-php-ext-install -j$(nproc) gd || (cat /tmp/config.log && exit 1)

# Install pdo_mysql
RUN docker-php-ext-install -j$(nproc) pdo_mysql

# Install mbstring
RUN docker-php-ext-install -j$(nproc) mbstring

# Install exif
RUN docker-php-ext-install -j$(nproc) exif

# Install pcntl
RUN docker-php-ext-install -j$(nproc) pcntl

# Install bcmath
RUN docker-php-ext-install -j$(nproc) bcmath

# Clean up
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

# Copy application code
COPY . /var/www

# Set working directory
WORKDIR /var/www

# Add crontab file in the cron directory
COPY crontab /etc/cron.d/laravel-scheduler-cron

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/laravel-scheduler-cron

# Apply cron job
RUN crontab /etc/cron.d/laravel-scheduler-cron

# Create the log file to be able to run tail
RUN touch /var/log/cron.log

# Run the command on container startup
CMD cron && tail -f /var/log/cron.log

# Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["php-fpm"]
